name: lib_smilingschool
description: An Infomentor API client written in Dart providing easy access to an api none of us truly understands
version: 1.1.0-pre.2
repository: https://github.com/edupatch/lib_smilingschool-dart

# We can't use this on the web because of CORS issues
platforms:
  android: 
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.5.0

dependencies:
  cookie_jar: ^4.0.8
  dio: ^5.8.0
  dio_cookie_manager: ^3.2.0
  intl: ^0.20.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.9.0
  lints: 5.0.0
  test: ^1.25.0
