name: lib_infomentor
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/edupatch/lib_infomentor-dart

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lib_driver:
    path: /home/ludv/coding/edupatch/lib_driver

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
