name: lib_smilingschool
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/edupatch/lib_smilingschool-dart

# We can't use this on the web because of CORS issues
platforms:
  android: 
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  cookie_jar: ^4.0.8
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
