name: lib_infomentor
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/edupatch/lib-infomentor/dart/lib-infomentor

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
